// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaN9W04n3mtwNK18xoRAu6oGFrI5imKws',
    appId: '1:449129892627:web:147ddb1c2721576996a8e6',
    messagingSenderId: '449129892627',
    projectId: 'clothing-store-app-97005',
    authDomain: 'clothing-store-app-97005.firebaseapp.com',
    storageBucket: 'clothing-store-app-97005.appspot.com',
    measurementId: 'G-L5BLGRK2MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwn6lI3hbWUGpHHo7HXjNQf4-QfPZP_DU',
    appId: '1:449129892627:android:3dbcfb1251ac2feb96a8e6',
    messagingSenderId: '449129892627',
    projectId: 'clothing-store-app-97005',
    storageBucket: 'clothing-store-app-97005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTBnnLNAFZidRIonLRITmqNpblnAM7eQ',
    appId: '1:449129892627:ios:26928e2e37fb54ca96a8e6',
    messagingSenderId: '449129892627',
    projectId: 'clothing-store-app-97005',
    storageBucket: 'clothing-store-app-97005.appspot.com',
    iosBundleId: 'com.example.clothingStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTBnnLNAFZidRIonLRITmqNpblnAM7eQ',
    appId: '1:449129892627:ios:26928e2e37fb54ca96a8e6',
    messagingSenderId: '449129892627',
    projectId: 'clothing-store-app-97005',
    storageBucket: 'clothing-store-app-97005.appspot.com',
    iosBundleId: 'com.example.clothingStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaN9W04n3mtwNK18xoRAu6oGFrI5imKws',
    appId: '1:449129892627:web:afa22924cdd9766196a8e6',
    messagingSenderId: '449129892627',
    projectId: 'clothing-store-app-97005',
    authDomain: 'clothing-store-app-97005.firebaseapp.com',
    storageBucket: 'clothing-store-app-97005.appspot.com',
    measurementId: 'G-GRG4EVLN01',
  );
}
